#!/bin/bash  
#SBATCH --job-name="dgg-job"  
#SBATCH --output="dgg-job.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 01:00:00

export PATH="$HOME/bin:$PATH"
export PATH="/home/rbarnes1/os/anaconda3/bin:$PATH"

cd /home/rbarnes1/dgg_best_poles2

export LD_LIBRARY_PATH=$HOME/os/anaconda3/lib:$LD_LIBRARY_PATH

./dgfinder.exe